Added fontSearch and --background option to sunrise Cosmetic fix to stamp. No significant change to reverse.

diff --git a/bin/stamp b/bin/stamp
--- a/bin/stamp
+++ b/bin/stamp
@@ -1,8 +1,8 @@
 #!/bin/bash
 
 syntaxError() {
-	echo  usage: $0 '[{--help|-?}|--set  value|{--verbose|-v}]+ inpath outpath'
-	echo 'set: { gravity | font | size | label | opacity | rotate }'
+	echo  usage: $0 '[{--help|-?}|--set value|{--verbose|-v}]+ inpath outpath'
+	echo 'set: { background | gravity | font | size | label | opacity | rotate }'
 	exit 1
 }
 if [ $# -eq 0 ]; then syntaxError ; fi
@@ -12,6 +12,22 @@ bomb() {
 	exit 1
 }
 
+searchForFont() # $1 = Name of font
+{
+	local F
+	for ext in '' .otf .ttf .dfont ; do 
+		for dir in '' /Library/Fonts /System/Library/Fonts /usr/X11/share/fonts/TTF ; do
+			F="$dir/$1$ext"
+			if [ -e "$F" ]; then 
+				echo "$F"
+				return
+			fi
+		done
+	done
+}
+
+##
+# use these temporary files
 emboss=/tmp/emboss.png
 watermark=/tmp/watermark.png
 text=/tmp/text.png
@@ -21,6 +37,7 @@ text=/tmp/text.png
 f="Arial"
 l="clanmills.com © 2012"
 g=south
+b=transparent
 s=400
 o=50
 r=0
@@ -29,55 +46,57 @@ files=()
 # http://mywiki.wooledge.org/BashFAQ/035
 while [ $# -gt 0 ]; do
     case "$1" in
-      -h|--help|-\?) syntaxError; exit 0 ;;
-      -v|--verbose)  v=1; shift ;;
-      -g|--gravity)  if [ $# -gt 1 ]; then g=$2; shift 2 ; else bomb $1 ; fi ;;
-      -f|--font)     if [ $# -gt 1 ]; then f=$2; shift 2 ; else bomb $1 ; fi ;;
-      -l|--label)    if [ $# -gt 1 ]; then l=$2; shift 2 ; else bomb $1 ; fi ;;
-      -s|--size)     if [ $# -gt 1 ]; then s=$2; shift 2 ; else bomb $1 ; fi ;;
-      -o|--opacity)  if [ $# -gt 1 ]; then o=$2; shift 2 ; else bomb $1 ; fi ;;
-      -r|--rotate)   if [ $# -gt 1 ]; then r=$2; shift 2 ; else bomb $1 ; fi ;;
-      --)            shift; break;;
-      -*)            echo "invalid option: $1" 1>&2; syntaxError; exit 1;;
-      *)             files+=("$1") ; shift ;;
+      -h|--help|-\?) 		syntaxError; exit 0 ;;
+      -v|--verbose)  		v=1; shift ;;
+      --nolabel)  			l=''; shift ;;
+      -b|--background|--bg)	if [ $# -gt 1 ]; then b="$2"; shift 2 ; else bomb $1 ; fi ;;
+      -g|--gravity)  		if [ $# -gt 1 ]; then g=$2; shift 2 ; else bomb $1 ; fi ;;
+      -f|--font)     		if [ $# -gt 1 ]; then f=$2; shift 2 ; else bomb $1 ; fi ;;
+      -l|--label)    		if [ $# -gt 1 ]; then l=$2; shift 2 ; else bomb $1 ; fi ;;
+      -s|--size)     		if [ $# -gt 1 ]; then s=$2; shift 2 ; else bomb $1 ; fi ;;
+      -o|--opacity)  		if [ $# -gt 1 ]; then o=$2; shift 2 ; else bomb $1 ; fi ;;
+      -r|--rotate)   		if [ $# -gt 1 ]; then r=$2; shift 2 ; else bomb $1 ; fi ;;
+      --)            		shift; break;;
+      -*)            		echo "invalid option: $1" 1>&2; syntaxError; exit 1;;
+      *)             		files+=("$1") ; shift ;;
     esac
 done
 
 if [ ${#files[@]} -ne 2 ]; then
-	echo "*** wrong number of inputs (${#files[@]}) ***"
+	echo "*** wrong number of input files (${#files[@]}) ***" 1>&2
 	syntaxError
 fi
 input="${files[0]}"
 output="${files[1]}"
 
-if [ "$v" != 0 ]; then
-	echo "$0 -g $g -f $f ${files[@]}"
-fi
-
 if [ ! -e "$input" ]; then
-	echo "*** $input does not exist ***"
+	echo "*** $input does not exist ***" 1>&2
 	exit 1
 fi
 
 if [[ -e "$output" && ("$(ls -i "$output"|cut -d' ' -f 1)" == "$(ls -i "$input"|cut -d' ' -f 1)") ]]; then
-	echo '*** input and output are the same file ***'
+	echo '*** input and output are the same file ***' 1>&2
 	exit 1
 fi
 
-F="/Library/Fonts/$f.ttf"
+F=$(searchForFont "$f")
 if [ ! -e "$F" ]; then
-	echo "font $f does not exist"
+	echo "*** font $f does not exist ***" 1>&2
 	exit 1
 fi
 f="$F"
 
+if [ "$v" != 0 ]; then
+	echo "$0 -g $g -f $F ${files[@]}"
+fi
+
 rm -rf    "$output"
 if [ "$l" != "" ]; then
-	convert   -background transparent -fill black -stroke white -strokewidth 2 -font "$f" -pointsize 100 -rotate "$r" "label:$l" "$text"
+	convert   -background transparent -fill black -stroke white -strokewidth 2 -font "$f" -pointsize 100 "label:$l" "$text"
 	convert   -emboss 10 "$text" "$watermark"
-	composite -dissolve "$o"  -gravity "$g" "$watermark" "$input" -resize "$s" "$output"
+	composite -dissolve "$o"  -gravity "$g" "$watermark" "$input" -resize "$s" -background $b -rotate "$r" "$output"
 else
-	convert   "$input" -resize "%s" -rotate "$r" "$output"
+	convert   -background $b "$input" -resize "%s" -rotate "$r" "$output"
 fi
 open      "$output"
 
