Added --city option to sunrise

diff --git a/bin/sunrise b/bin/sunrise
--- a/bin/sunrise
+++ b/bin/sunrise
@@ -2,7 +2,7 @@
 
 syntaxError() {
 	echo "usage: $0 [{--help|-?}|{--set|-s} n|{--verbose|-v}]+"
-	echo "set: day | month | year | from | to | lAtitude | lOngtitude | zone | [s|daylight]"
+	echo "set: day | month | year | from | to | lAtitude | lOngtitude | zone | city | [s|daylight]"
 	exit 1
 }
 
@@ -23,6 +23,7 @@ f=0
 t=0
 y=0
 s=-1
+c=''
 # http://mywiki.wooledge.org/BashFAQ/035
 while true; do
     case "$1" in
@@ -37,11 +38,38 @@ while true; do
       -y|--year)     if [ $# -gt 1 ]; then y=$2; shift 2 ; else bomb $1 ; fi ;;
       -d|--day)      if [ $# -gt 1 ]; then d=$2; shift 2 ; else bomb $1 ; fi ;;
       -s|--daylight) if [ $# -gt 1 ]; then s=$2; shift 2 ; else bomb $1 ; fi ;;
+      -c|--city)     if [ $# -gt 1 ]; then c=$2; shift 2 ; else bomb $1 ; fi ;;
       --)            shift; break;;
       -*)            echo "invalid option: $1" 1>&2; syntaxError; exit 1;;
       *)             break;;
     esac
 done
+
+##
+# look up the city
+cities="/Users/rmills/bin/cities.txt"
+if [ "$c" != "" ]; then
+	if [ ! -e "$cities" ]; then
+		echo file "$cities" not found
+		exit 1
+	fi
+	count=$(grep "$c" "$cities" |wc -l)
+	if [ "$count" -eq "0" ]; then
+		echo "*** city $c not found"
+		exit 1
+	elif [ "$count" -eq "1" ]; then
+		echo "found unique city"
+		       grep "$c" "$cities"
+		x+=( $(grep "$c" "$cities") )
+		a=${x[1]}
+		l=${x[2]}
+		echo "lat = " $a " long = " $l
+	else 
+		echo "too many cities"
+		grep "$c" "$cities"
+		exit 1
+	fi
+fi
 
 ##
 # modify defaults
